name: Update AC Badge

on:
  schedule:
    - cron: "0 * * * *"  # 毎時実行（日本時間なら +9h）
  workflow_dispatch:     # 手動実行も可

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        run: python count_solved.py
      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add solved.json
          git commit -m "Update AC badge"
          git push
